name: Test

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
    branches:
      - main
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  test_matrix:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 20
          - 18
          - 16

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm ci

      - name: Check codestyle compliance
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Upload coverage reports to Codecov
        if: ${{ matrix.node-version == 20 }}
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/coverage-final.json
          fail_ci_if_error: true

  # separate job to set as required in branch protection,
  # as the build names above change each time Node versions change
  test:
    runs-on: ubuntu-latest
    needs:
      - test_matrix
    if: always()
    steps:
      - name: All matrix versions passed
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Some matrix version failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
